version: '3'

services:
  mysql:
    image: mysql/mysql-server:8.0.28-1.2.7-server
    environment:
      LANG: 'C.UTF-8'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql_volume:
    driver: local
